### ISSUE TITLE
关于 README 中的图床问题

### ISSUE THREAD

**Issue by Dup4** [ZhongFuCheng3y/austin#1]
在 Gitee 中看到相关的 [Issue](https://gitee.com/zhongfucheng/austin/issues/I4LPBX)

有点好奇，为什么不将图片放在仓库中，然后在 README 中引用？

另外，有点好奇这个项目，Gitee 和 Github 两边维护，如何进行同步？

是在 git 的 config 中配置两个 remote 地址，push 两次吗

那这样的话，对于 PR，岂不是也要人工同步？

**Comment by ZhongFuCheng3y** [comment]
1. 直接使用图床会更加方便
2. 是配置两个remote地址，push两次的（这块工作量其实挺少的）
