### ISSUE TITLE
sms推送问题

### ISSUE THREAD

**Issue by wuguipeng** [ZhongFuCheng3y/austin#19]
现在的短信推送都是需要提前备案的，备案通过之后，有一个templateId，但是我看templateId是和配置写在一起的，加载配置的时候就加载templateId，不能选择想要发送的templateId吗？

**Comment by ZhongFuCheng3y** [comment]
接入短信这块主要是做了个演示。（需要根据实际情况自己改动）

像到公司生产级别的，发送通知类、营销类就可以没有短信模板的（去商务）

**Comment by ZhongFuCheng3y** [comment]
> 现在的短信推送都是需要提前备案的，备案通过之后，有一个templateId，但是我看templateId是和配置写在一起的，加载配置的时候就加载templateId，不能选择想要发送的templateId吗？

**Comment by ZhongFuCheng3y** [comment]
> 现在的短信推送都是需要提前备案的，备案通过之后，有一个templateId，但是我看templateId是和配置写在一起的，加载配置的时候就加载templateId，不能选择想要发送的templateId吗？

接入短信这块主要是做了个演示。（需要根据实际情况自己改动）

像到公司生产级别的，发送通知类、营销类就可以没有短信模板的（去商务）
