### ISSUE TITLE
如何使用项目演示地址配置邮箱渠道消息

### ISSUE THREAD

**Issue by huaka1** [ZhongFuCheng3y/austin#23]
我想利用项目的演示地址完成一次测试，具体配置如下：
## 渠道账号管理：
![image](https://user-images.githubusercontent.com/62634519/219915536-85eccdad-067b-42e0-8ed9-6e2992c3d934.png)
## 模板：
![image](https://user-images.githubusercontent.com/62634519/219916132-f5d583ed-7965-4ecf-8c4d-4ddf64cd8b21.png)
## 结果：
![image](https://user-images.githubusercontent.com/62634519/219916306-a3df3578-ab89-4615-a868-2d6edace31d6.png)

我猜测应该是渠道账号设置问题，小白不是很了解配置qq邮箱管理渠道账号应该如何对应qq邮箱中的设置（即使项目给了样例），希望解答！！！

**Comment by ZhongFuCheng3y** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/33118128/219951160-28a917de-b2a3-4ac9-8996-c998e442a72d.png">
<img width="835" alt="image" src="https://user-images.githubusercontent.com/33118128/219951174-8b9ffc89-4943-4bc3-b068-961964ee0d85.png">
