### ISSUE TITLE
目前仅支持了短信么？还是微信模板消息、订阅消息已经支持了，我看SQL里面只有sms_record表

### ISSUE THREAD

**Issue by WiSmile** [ZhongFuCheng3y/austin#24]

**Comment by ZhongFuCheng3y** [comment]
已支持渠道如下：
![image](https://user-images.githubusercontent.com/33118128/220351708-376b930b-d48e-4b08-b827-1f4fcab8a5ff.png)

只有sms_record表原因是我认为暂且只有短信渠道需要记录下发记录到DB（相对重要些）
