### ISSUE TITLE
Maven Install error

### ISSUE THREAD

**Issue by starit** [ZhongFuCheng3y/austin#27]
没有找到安装的步骤，于是按照我自己的理解，使用`mvn install`时会报错

```
[ERROR] Failed to execute goal on project austin-data-house: Could not resolve dependencies for project com.java3y.austin:austin-data-house:jar:0.0.1-SNAPSHOT: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in nexus-163 (http://mirrors.163.com/maven/repository/maven-public/) -> [Help 1]
```

**Comment by ZhongFuCheng3y** [comment]
> 没有找到安装的步骤，于是按照我自己的理解，使用`mvn install`时会报错
> 
> ```
> [ERROR] Failed to execute goal on project austin-data-house: Could not resolve dependencies for project com.java3y.austin:austin-data-house:jar:0.0.1-SNAPSHOT: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in nexus-163 (http://mirrors.163.com/maven/repository/maven-public/) -> [Help 1]
> ```

mvn镜像配置参考：
<mirror>
  <id>alimaven</id>
  <mirrorOf>central</mirrorOf>
  <name>aliyun maven</name>
  <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
</mirror>

 
<mirror>
    <id>repo1</id>
    <mirrorOf>central</mirrorOf>
    <name>Human Readable Name for this Mirror.</name>
    <url>http://repo1.maven.org/maven2/</url>
</mirror>


<mirror>
    <id>repo2</id>
    <mirrorOf>central</mirrorOf>
    <name>Human Readable Name for this Mirror.</name>
    <url>http://repo2.maven.org/maven2/</url>
</mirror>

**Comment by starit** [comment]
还是一样的报错，是不是mac上不支持，理论上java环境应该都一样才对

**Comment by ZhongFuCheng3y** [comment]
> 

不会的，我本地就是Mac

**Comment by ZhongFuCheng3y** [comment]
> 还是一样的报错，是不是mac上不支持，理论上java环境应该都一样才对

直接在austin目录下install，而不是在austin-data-house试试。

**Comment by laoxiaokang** [comment]
我也遇到了同样的问题 ，修改了maven的配置后也没有解决 @ZhongFuCheng3y ，相信这个问题不是个例

**Comment by laoxiaokang** [comment]
贴一下错误:
[IJ]-1-ARTIFACT_DOWNLOADED-[IJ]-path=-[IJ]-artifactCoord=org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde-[IJ]-error=Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to conjars (http://conjars.org/repo): Connect to conjars.org:80 [conjars.org/54.235.127.59] failed: Connection timed out: connect
