### ISSUE TITLE
当消息中间件为Kafka，用户不传tagId，是否会报空指针异常？

### ISSUE THREAD

**Issue by Ryan-Jony** [ZhongFuCheng3y/austin#30]
@Override
    public void send(String topic, String jsonValue, String tagId) {  //若此时用户不传tagId
        if (StrUtil.isNotBlank(tagId)) {
            List<Header> headers = Arrays.asList(new RecordHeader(tagIdKey, tagId.getBytes(StandardCharsets.UTF_8)));
            kafkaTemplate.send(new ProducerRecord(topic, null, null, null, jsonValue, headers));
        } else {
            kafkaTemplate.send(topic, jsonValue);
        }
    }

    @Override
    public void send(String topic, String jsonValue) { //不传tagId
        send(topic, jsonValue, null);
    }
-----------------------------------------------------------------------------------------------------------------------------------------
    @Bean
    public ConcurrentKafkaListenerContainerFactory filterContainerFactory(@Value("${austin.business.tagId.key}") String tagIdKey,
                                                                          @Value("${austin.business.tagId.value}") String tagIdValue) {
        ConcurrentKafkaListenerContainerFactory factory = new ConcurrentKafkaListenerContainerFactory();
        factory.setConsumerFactory(consumerFactory);
        factory.setAckDiscarded(true);

        factory.setRecordFilterStrategy(consumerRecord -> {
            if (Optional.ofNullable(consumerRecord.value()).isPresent()) {
                for (Header header : consumerRecord.headers()) {
                    if (header.key().equals(tagIdKey) && new String(header.value()).equals(new String(tagIdValue.getBytes(StandardCharsets.UTF_8)))) {  //若用户不传tagId，这行代码是否会报空指针异常？
                        return false;
                    }
                }
            }
            //返回true将会被丢弃
            return true;
        });
        return factory;
    }

**Comment by Ryan-Jony** [comment]
if (header.key().equals(tagIdKey) && new String(header.value()).equals(new String(tagIdValue.getBytes(StandardCharsets.UTF_8)))) {  //若用户不传tagId，这行代码是否会报空指针异常？
                    return false;
                }

**Comment by ZhongFuCheng3y** [comment]
> if (header.key().equals(tagIdKey) && new String(header.value()).equals(new String(tagIdValue.getBytes(StandardCharsets.UTF_8)))) { //若用户不传tagId，这行代码是否会报空指针异常？ return false; }

不会空指针，tagId来源于application.properties的配置(**默认是有值的**）：
```properties
### TODO kafka tag filter,if you need, replace  tagIdValue ,eg:com.java3y.austin.yyy
austin.business.tagId.key=kafka_tag_id
austin.business.tagId.value=com.java3y.austin.3y
```
如果将其置空，如：
```properties
### TODO kafka tag filter,if you need, replace  tagIdValue ,eg:com.java3y.austin.yyy
austin.business.tagId.key=
austin.business.tagId.value=
```
由于上述的过滤器，会导致topic为 austinBusiness 消息被过滤掉（因为没有header，过滤器 直接返回 true）
