### ISSUE TITLE
没什么数据，列表查询耗时近10秒

### ISSUE THREAD

**Issue by lindadev77** [ZhongFuCheng3y/austin#36]
![image](https://user-images.githubusercontent.com/9762702/235413791-f895859b-6f9b-4c2f-94a5-7c72055ea19a.png)

刚本地跑通，啥数据都没有，第一次进模板列表接口转近10秒，切到渠道账号走一下列表查询，再回来模板列表，奇怪没啥数据为啥每次都能耗近10秒，难道是切页面每次数据源都能重新建立连接

**Comment by lindadev77** [comment]
我这个本地接口docker启动的，页面简单演示做的确实简单，列表查询没分页控件处理，渠道账号管理搜索按钮也没有
![image](https://user-images.githubusercontent.com/9762702/235414200-ec96203d-e1d7-4114-8533-6cc0f60ceb82.png)

![image](https://user-images.githubusercontent.com/9762702/235414248-5a95e2e9-2dfa-4d9b-a57e-a32360d6f4b2.png)

**Comment by seafeee** [comment]
确实 我也发现这个问题了 排查之后发现这个打印日志的操作非常耗时 需要2~3s
![image](https://github.com/ZhongFuCheng3y/austin/assets/49563049/ccb01f31-c8e3-4f76-ac49-3381eb850bfa)

**Comment by ZhongFuCheng3y** [comment]
暂已将graylog配置成 test 环境才发送
