### ISSUE TITLE
代码结构和可读性可以，但老夫有些问题看阁下又当如何应对

### ISSUE THREAD

**Issue by fantj2016** [ZhongFuCheng3y/austin#44]
1. 占位符未被替换完成之后，是不是要拦截，不然占位符会有直接发出去的风险。
2. 从代码功能来看，这个系统应该是push的最下面的中台，不应该有模版id的概念，也不应该有msgType的概念
3. receiver被过滤掉后接口应该将receiver过滤原因返回,response应该是receiver维度的一个push结果

**Comment by ZhongFuCheng3y** [comment]
1， 如果占位符未被替换，是直接抛出异常的。
2，并不是。这个系统不止是为push（通知栏消息推送）服务的，短信/邮件/钉钉等渠道都有。有模版id的概念，才会有全链路最终这种功能的实现，甚至才称得上消息推送平台。
3，receiver过滤原因返回 这个是细节优化问题了，感兴趣可以提个PR搞搞

**Comment by ZhongFuCheng3y** [comment]
> 1. 占位符未被替换完成之后，是不是要拦截，不然占位符会有直接发出去的风险。
> 2. 从代码功能来看，这个系统应该是push的最下面的中台，不应该有模版id的概念，也不应该有msgType的概念
> 3. receiver被过滤掉后接口应该将receiver过滤原因返回,response应该是receiver维度的一个push结果

1， 如果占位符未被替换，是直接抛出异常的。
2，并不是。这个系统不止是为push（通知栏消息推送）服务的，短信/邮件/钉钉等渠道都有。有模版id的概念，才会有全链路最终这种功能的实现，甚至才称得上消息推送平台。
3，receiver过滤原因返回 这个是细节优化问题了，感兴趣可以提个PR搞搞

**Comment by fantj2016** [comment]
第一点没问题，我后面看到有这块实现了
第二点，可能大家理解不太一样，因为你入参已经将占位符值map传进来，所以我认为二方的信息在这个系统就不该有，它应该是更通用的一层，和二方对接的业务，应该是它上层来承接。所以模版不应该在api里面去呈现，因为他属于上层的概念，在api这一层，应该根据渠道然后把模版打平为占位符，来实现push。这里前后有点矛盾，所以我说系统定位不太清楚，如果api是承接业务过来的，那不应该让业务感知占位符和模版id，因为B端肯定在你这边，不应该让业务感知这些概念。

其次，批量push的接口，你的设计是单模版+多用户，这样的计算量是 用户数x模版数。如果面对很大的push任务和时间压力，这块可以优化为用户数的。
