### ISSUE TITLE
你好，maven打包提示关联的jar,已经找不到了。

### ISSUE THREAD

**Issue by HandSomeBC** [ZhongFuCheng3y/austin#55]
Failed to execute goal on project austin-data-house: Could not resolve dependencies for project com.java3y.austin:austin-data-house:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.hive:hive-exec:jar:2.3.4 -> org.apache.calcite:calcite-core:jar:1.10.0 -> org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Failed to read artifact descriptor for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [datanucleus (http://www.datanucleus.org/downloads/maven2, default, releases), glassfish-repository (http://maven.glassfish.org/content/groups/glassfish, default, disabled), glassfish-repo-archive (http://maven.glassfish.org/content/groups/glassfish, default, disabled), apache.snapshots (http://repository.apache.org/snapshots, default, snapshots), central (http://repo.maven.apache.org/maven2, default, releases), conjars (http://conjars.org/repo, default, releases+snapshots)] -> [Help 1]

**Comment by ZhongFuCheng3y** [comment]
这个是 austin-data-house 模块里的，hive的依赖没下下来；
1、在打包的时候，可以把这个模块给剔除
2、实在下载不下来，可以把包加到对应的位置上
![image](https://github.com/ZhongFuCheng3y/austin/assets/33118128/fcedd72c-bed9-449c-8a8b-2938d7ce437d)

[pentaho-aggdesigner-algorithm_2.zip](https://github.com/ZhongFuCheng3y/austin/files/13110443/pentaho-aggdesigner-algorithm_2.zip)
