### ISSUE TITLE
 Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in nexus-aliyun (https://maven.aliyun.com/repository/public) 

### ISSUE THREAD

**Issue by engineerping** [ZhongFuCheng3y/austin#58]
怎样配置 maven 的 settings.xml 才能方便地找到这个 artifact?

**Comment by engineerping** [comment]
downloaded manually -> install to maven localRepository manually -> solved

**Comment by xiaoxiamo** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
  
  <mirrors>
    
    
    <mirror>
      <id>aliyunmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Aliyun Maven</name>
      <url>https://maven.aliyun.com/repository/public</url>
    </mirror>

    
    <mirror>
      <id>alimaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Aliyun Nexus Maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
    </mirror>

    
    <mirror>
      <id>aliyunmaven-spring-plugin</id>
      <mirrorOf>*</mirrorOf>
      <name>Aliyun Spring Plugin</name>
      <url>https://maven.aliyun.com/repository/spring-plugin</url>
    </mirror>

    
    <mirror>
      <id>huaweicloud</id>
      <mirrorOf>central</mirrorOf>
      <name>Huawei Cloud Maven</name>
      <url>https://repo.huaweicloud.com/repository/maven/</url>
    </mirror>

    
    <mirror>
      <id>tencentmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Tencent Maven</name>
      <url>https://mirrors.cloud.tencent.com/nexus/repository/maven-public/</url>
    </mirror>

  </mirrors>

  <profiles>

    
    <profile>
      <id>default</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  
  </profiles>

  <activeProfiles>
    <activeProfile>default</activeProfile>
  </activeProfiles>

</settings>

**Comment by xiaoxiamo** [comment]
<mirrors>
    
    
    <mirror>
      <id>aliyunmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Aliyun Maven</name>
      <url>https://maven.aliyun.com/repository/public</url>
    </mirror>

    
    <mirror>
      <id>alimaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Aliyun Nexus Maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
    </mirror>

    
    <mirror>
      <id>aliyunmaven-spring-plugin</id>
      <mirrorOf>*</mirrorOf>
      <name>Aliyun Spring Plugin</name>
      <url>https://maven.aliyun.com/repository/spring-plugin</url>
    </mirror>

    
    <mirror>
      <id>huaweicloud</id>
      <mirrorOf>central</mirrorOf>
      <name>Huawei Cloud Maven</name>
      <url>https://repo.huaweicloud.com/repository/maven/</url>
    </mirror>

    
    <mirror>
      <id>tencentmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Tencent Maven</name>
      <url>https://mirrors.cloud.tencent.com/nexus/repository/maven-public/</url>
    </mirror>

  </mirrors>

**Comment by xiaoxiamo** [comment]
<mirror>
  <id>aliyunmaven</id>
  <mirrorOf>central</mirrorOf>
  <name>Aliyun Maven</name>
  <url>https://maven.aliyun.com/repository/public</url>
</mirror>


<mirror>
  <id>alimaven</id>
  <mirrorOf>central</mirrorOf>
  <name>Aliyun Nexus Maven</name>
  <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
</mirror>


<mirror>
  <id>aliyunmaven-spring-plugin</id>
  <mirrorOf>*</mirrorOf>
  <name>Aliyun Spring Plugin</name>
  <url>https://maven.aliyun.com/repository/spring-plugin</url>
</mirror>


<mirror>
  <id>huaweicloud</id>
  <mirrorOf>central</mirrorOf>
  <name>Huawei Cloud Maven</name>
  <url>https://repo.huaweicloud.com/repository/maven/</url>
</mirror>


<mirror>
  <id>tencentmaven</id>
  <mirrorOf>central</mirrorOf>
  <name>Tencent Maven</name>
  <url>https://mirrors.cloud.tencent.com/nexus/repository/maven-public/</url>
</mirror>

详见：doc/maven

**Comment by xiaoxiamo** [comment]
<mirrors>
    
    
    <mirror>
      <id>aliyunmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Aliyun Maven</name>
      <url>https://maven.aliyun.com/repository/public</url>
    </mirror>

    
    <mirror>
      <id>alimaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Aliyun Nexus Maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
    </mirror>

    
    <mirror>
      <id>aliyunmaven-spring-plugin</id>
      <mirrorOf>*</mirrorOf>
      <name>Aliyun Spring Plugin</name>
      <url>https://maven.aliyun.com/repository/spring-plugin</url>
    </mirror>

    
    <mirror>
      <id>huaweicloud</id>
      <mirrorOf>central</mirrorOf>
      <name>Huawei Cloud Maven</name>
      <url>https://repo.huaweicloud.com/repository/maven/</url>
    </mirror>

    
    <mirror>
      <id>tencentmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>Tencent Maven</name>
      <url>https://mirrors.cloud.tencent.com/nexus/repository/maven-public/</url>
    </mirror>

  </mirrors>

详见：doc/maven/settings.xml
