### ISSUE TITLE
调用逻辑是不是有问题？

### ISSUE THREAD

**Issue by lph1140639876** [ZhongFuCheng3y/austin#71]
https://github.com/ZhongFuCheng3y/austin/blob/3cc1f7f06798e3254cd6c035ae9a209d51b1dfa7/austin-handler/src/main/java/com/java3y/austin/handler/config/SensitiveWordsConfig.java#L127

**Comment by xiaoxiamo** [comment]
抱歉，确有问题，已修改。应用长期运行，还会有资源泄漏风险。🤡
