### ISSUE TITLE
没有这个jar包/austin-web-0.0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by ywd1988** [ZhongFuCheng3y/austin#74]
![de9223f5b6012cd785250d28677cd3c](https://github.com/user-attachments/assets/b4e29558-9e47-4be6-a229-2ccc0c217bbf)
没有这个文件吗？

**Comment by xiaoxiamo** [comment]
需自行编译整个项目，生成该Jar包。
![image](https://github.com/user-attachments/assets/5f2dcdcd-f49d-4760-93b4-b8e14e24517b)

**Comment by ywd1988** [comment]
![image](https://github.com/user-attachments/assets/6688fac4-0bf8-4fd3-9c6a-7d484c7936da)
为啥没有target 这个文件夹？

**Comment by ywd1988** [comment]
> 需自行编译整个项目，生成该Jar包。 ![图像](https://private-user-images.githubusercontent.com/52187812/391019382-5f2dcdcd-f49d-4760-93b4-b8e14e24517b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzM2MjUsIm5iZiI6MTczMjg3MzMyNSwicGF0aCI6Ii81MjE4NzgxMi8zOTEwMTkzODItNWYyZGNkY2QtZjQ5ZC00NzYwLTkzYjQtYjhlMTRlMjQ1MTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5NDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MzFmMGMxNDgzNGYzOGQyNWM0MTIxZWZmYmI4NjFiZWM1ZGNiZWMxOTY1NTUzOWY1ZjFiOGUzMWU5YTY0NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.quXPgappwGp0pE1YwSbQsqSgDoBzogh6h7BpW4e3Q8k)

![image](https://github.com/user-attachments/assets/e88e1d44-f603-425e-8672-65b1ed3d9b91)

**Comment by ywd1988** [comment]
> target整个文件夹，都是项目编译后生成。

好的感谢
